### ISSUE TITLE
Supplemental Guidance Pull Request Question

### ISSUE THREAD

**Issue by Myndex** [w3c/low-vision-a11y-tf#105]
In the meeting we were encouraged to make edits to the supplemental guidance table, and I created a pull request:

https://github.com/w3c/low-vision-a11y-tf/pull/104

Are we *not* supposed to make edits to this table? Because all of my edits were reverted in this pull request.

???

**Comment by shawna-slh** [comment]
https://github.com/w3c/low-vision-a11y-tf/pull/104#issuecomment-926273605
