### ISSUE TITLE
Brief Section Overviews for the Requirements Document

### ISSUE THREAD

**Issue by lauracarlson** [w3c/low-vision-a11y-tf#2]
On November 20, 2015, [Jim Allan wrote](https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2015Nov/0024.html):

> here are some tasks that the group will need to  address shortly. If you have time during the next 2 weeks please pick one and create something!!
> [snip]
> 3. Sectional overviews (7 of them) - need 1-2 sentences for each section. The sectional overviews may be combined in larger overveiw later (or not), but it is important to capture terse statements for each section.

The following is a start on writing brief section introductions for the [Accessibility Requirements for Low Vision Users](http://w3c.github.io/low-vision-a11y-tf/requirements.html) document.
### 2.1 Luminance and Color

Because people with low vision are, by nature, an extremely-diverse group with a wide range of needs, user control of luminance and color is required. Whenever adjacent colors convey different meanings, such meanings must be distinguishable.
### 2.2 Tracking

To read and to follow text, users require content to rewrap and reflow; and text areas must adapt to accommodate. User control of line length, text alignment, and hyphenation, is necessary for tracking.
### 2.3 Perceiving (Letter Characteristics)

User control of text size, font face, text style, and capitalization, is required for legibility.
### 2.4 Spacing for Reading

User control of letter, word, and element spacing; as well as leading and margins; is required for reading.
### 2.5 Distinguishing

User customization and control of text elements, text proportions, borders, and indentation, is required to differentiate parts of content.
### 2.6 Point of Regard and Proximity

The point of regard must be maintained, and the proximity of related information must be perceivable.
### 2.7 Printing

For printed content to be perceivable, user customization is required.

Ideas for improvement?

**Comment by slhenry** [comment]
copyedits from John: https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2015Dec/0001.html

**Comment by shawna-slh** [comment]
Thanks for getting this started, Laura!

For these section intros, I wonder if we want a description the overall issue, rather than a summary of user requirements? I guess it depends on what we decide to do with the Overview…

I'll try to make some time to work on it later this week and come up with some specific ideas for discussion.

**Comment by lauracarlson** [comment]
I updated the text per John's suggestions. I agree that the overview will impact how we proceed.

Thank you!

**Comment by shawna-slh** [comment]
Here's a _rough_ draft of what I was thinking for brief descriptions for each section.

2.1 Luminance and Color
Luminance is basically brightness. It is explained more in the [Light sensitivity and contrast sensitivity] section above.

2.2 Tracking
Tracking is following along lines of text, including getting from the end of one line to the beginning of the next line of text.

2.3 Perceiving
Perceiving is being able to recognize individual letters based on their characteristics; it is legibility.

2.4 Spacing for Reading
Space between lines and space between words impacts readability.

2.5 Identifying Elements
Identifying elements is about distinguishing things like headings and lists. 

2.6 Point of Regard and Proximity
The point of regard is the area that the user is viewing. (More info is available in: IndieUI wiki and UAAG 2.) Proximity is the space between items. In user interface generally, proximity is about using space to group related content and separate unrelated content.

2.7 Printing
[don't think we need to describe printing. :-]

**Comment by lauracarlson** [comment]
Hi Shawn,

I like the idea! 

The originals may be more suitable for a check list, if we ever want to make one.

Thanks.

**Comment by shawna-slh** [comment]
added to http://w3c.github.io/low-vision-a11y-tf/requirements.html#user-needs
