### ISSUE TITLE
Color blindness - not include stats?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/low-vision-a11y-tf#20]
Currently the <a href="http://w3c.github.io/low-vision-a11y-tf/requirements.html#color-vision">color vision section<a/> includes stats.

In the other sections (visual acuity, field of vision, sensitivity, etc.), we don't say anything about incidence/stats. I think given that many/most people with low vision have multiple impairments in these categories, we do not want to include stats in the individual sections. 

Color blindness is different because many people have just colorblindness and not the others. Also, the numbers for colorblindness are relatively high.

Should we include the stats for colorblindness?
Or should we not include those stats to be consistent with the other sections?

**Comment by allanj-uaag** [comment]
Yes we should include stats. Color blindness is something easy to tease out. It is one sentence. The other sections fall under the global stat of Low Vision. Color blindness is not included in the WHO stats.

**Comment by lauracarlson** [comment]
I think we should should include the color stats as we specifically added info on incidence of color disabilities after discussion at our January 6 meeting [1] [2].

[1] https://www.w3.org/2016/01/06-lvtf-minutes.html#item03
[2]  https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Jan/0014.html

**Comment by mraccess77** [comment]
yes, Includes stats on color perception disabilities.

**Comment by shawna-slh** [comment]
RESOLUTION 10 Feb teleconference https://www.w3.org/2016/02/10-lvtf-minutes.html#item01
