### ISSUE TITLE
Numbering Edit in 2.4.4 Field of Vision Section and 2.4.5 Color Vision Section

### ISSUE THREAD

**Issue by bakkenb** [w3c/low-vision-a11y-tf#28]
I know you are not ready for detailed edits yet, but I didn't want to forget about this later and not bring it up as an issue. 

In section 2.4.4 Field of Vision:

> User needs related to field of vision are addressed in the following sections:
> 2.2 Tracking - rewrap for one direction scrolling, reflow to single column, flexible text areas, line length, justification, hyphenation
> 2.6 Point of Regard and Proximity - maintain point to regard, proximity of related information, scrollbars

The referenced linked section numbers should be 3.2 and 3.6.

Similar issue in section 2.4.5 Color Vision

**Comment by shawna-slh** [comment]
Thanks for the catch! :-)
