### ISSUE TITLE
References to Success Criteria

### ISSUE THREAD

**Issue by bakkenb** [w3c/low-vision-a11y-tf#29]
I am not sure if this should be added before FPWD or after. Or if it should be added at all. But my question is, when applicable should the "user needs" statements or other section content reference specific SCs? 

For example, in section 3.1.3 Not Relying on Color, should it point to or reference [SC 1.4.1](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-without-color)? Should it reference the SC or maybe more importantly referent the [Understanding 1.4.1 page](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html)?

It would be helpful to identify the alignment to WCAG when possible.

**Comment by shawna-slh** [comment]
Thanks for the review and comment, Brent.

These user needs are independent of WCAG. (Actually, one motivation for the work is to identify things that potentially need to be added through a WCAG Extension or other.)

The [Status](http://w3c.github.io/low-vision-a11y-tf/requirements.html#h-sotd) section says:

<blockquote>
This document will provide the foundation for planned future work including:
* Gap Analysis – document how user needs are covered or not in Web Content Accessibility Guidelines (WCAG), User Agent Accessibility Guidelines (UAAG), and Authoring Tool Accessibility Guidelines (ATAG)
...
</blockquote>

**Comment by bakkenb** [comment]
Makes sense. Thank you for the explanation Shawn.
