### ISSUE TITLE
label positioning

### ISSUE THREAD

**Issue by AndrewArch** [w3c/low-vision-a11y-tf#30]
re 3.6.2 Proximity of Related Information - http://w3c.github.io/low-vision-a11y-tf/requirements.html#proximity-of-related-information

Consider an additional item about form labels along the lines of "position and 'required/option' notice adjacent to the label for forms fields". E.g, 18f (https://playbook.cio.gov/designstandards/form-templates/) positions the description of what is to be entered at the LHS of the text field and 'required' at the RHS - some people will just miss this visually (for cognitive, vision or scanning reasons), but some screen magnifier users will miss it completely as they scroll down the LHS of the page (LHS in this case as the form is in English) depending on their degree of magnification.

**Comment by allanj-uaag** [comment]
I believe we have this covered in the first bullet in 3.6.2

> Related information — such as labels and  controls, or matching tests in two columns, or feedback — is in close proximity.

Adding some images would help illustrate the issue. Laura has created some... https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/LVTF_Open_Issues#1._Distant_Proximity

**Comment by shawna-slh** [comment]
We could add "required" if we think it's important to point out. I think maybe not worth the added complexity, though.

**Comment by shawna-slh** [comment]
Added "instructions for data fields" to existing [3.6.2](http://w3c.github.io/low-vision-a11y-tf/requirements.html#proximity-of-related-information):

> Related information — such as labels and controls, instructions for data fields, matching tests in two columns, and feedback on input errors — is in close proximity.

Also added note to consider including required field indication in the examples.
