### ISSUE TITLE
Legibility 

### ISSUE THREAD

**Issue by WayneEDick** [w3c/low-vision-a11y-tf#31]
<h1>Types of Legibility</h1>

<p>Legge[Chapter 4, Psychophysics of Reading] defines legibility as follows:</p>

<blockquote>“Legibility” refers to perceptual properties of text that influence readability. Text which is hard to read because of obscure vocabulary, or complex syntax or meaning may be incomprehensible, but still highly legible. Legibility depends on both local and global properties of text. Local properties refer to characteristics of individual letters or pairs of letters such as font, print size, and letter spacing. Global properties refer to layout characteristics such as line length, line spacing, and page format.</blockquote>

<p>If text is legible a person can read at an optimal speed and make few errors. However, legibility is a continuum. There is text that supports letter and word recognition somewhat, but the text can only be read slowly and the reader may make many mistakes before getting a word correctly. This type of text is usually composed of the tiniest print sizes that are perceivable or may be combine close spacing, long lines, poor contrast etc.  While minimally legible in a formal sense, such text could not support effective reading. The Low Vision Task Force  (LVTF)  will call this text  “barely legible”.</p>

<p>It is possible to have text that is very legible, but may not supportive of reading for long periods of time. A text may be the right size, have the appropriate font, letter and line spacing, but if the page is in a multi-column format many readers with peripheral field low will have a difficult time navigating an article when they need to move from column to column. This can produce fatigue while reading a long article and result in not finishing the task.  The same article formatted with the same size, font, letter and line spacing, and line length, but with only one column would enable reading with much less difficulty and sustain completing the reading task. For people with photophobia, a similar situation occurs with too much brightness. The person may be able to read rapidly with few mistakes, but sustained reading produces head aches and eye pain. Text that is very legible and supports reading long documents is denoted as sustainable by the LVTF.</p>

<p>Legibility thus has three states: Text that can be read rapidly with few mistakes is called legible. Text that admits recognition with extreme difficulty is barely legible, and text that is legible and can be read for extended periods of time is sustainable.</p>

<p>The terms “barely visible” and “sustainable” are new but are useful concepts for the LVTF. The task force is charged with prescribing effective typographic environments for people with low vision along with the content and user agent requirements necessary to produce them. The task force considers text that is barely legible and text that is legible but not sustainable to barriers to reading.  A primary goal of the LVTF will be to ensure users with low vision can have access to sustainable text.</p>

<p>It is important to note that the terms barely visible, legible and sustainable are associated with the individual reader. Reading rapidly has a different meaning for a person with central field loss as compared to a normal reader. Numerous contrast studies have shown that contrast levels that are legible for normal readers are barely visible to most people with low vision.  A primary goal of the LVTF will be to define the constraints on content and user agents that are necessary to produce sustainable text for each user of web content.</p>

**Comment by shawna-slh** [comment]
overtaken by issue https://github.com/w3c/low-vision-a11y-tf/issues/37
