### ISSUE TITLE
Section 2.3 Cause and Progression of Low Vision - minor wording change

### ISSUE THREAD

**Issue by shawna-slh** [w3c/low-vision-a11y-tf#33]
current wording:

<blockquote>Most low vision is caused by eye diseases and health conditions such as cataracts, glaucoma, and diabetes. These are more prevalent in older people. Some low vision is from birth defects or injuries.</blockquote>

[Section 2.3 Cause and Progression of Low Vision](http://w3c.github.io/low-vision-a11y-tf/requirements.html#cause-and-progression-of-low-vision) - I’d like to reword differently:

"Most low vision conditions are caused by eye diseases and health conditions such as cataracts, glaucoma, macular degeneration and diabetes. While some low vision conditions come from birth defects or injuries, an increasing number of such conditions are found in seniors, as eye diseases and health conditions become more prevalent as people get older."

from Denis Boudreau https://lists.w3.org/Archives/Public/public-low-vision-comments/2016JanMar/0003.html

**Comment by mraccess77** [comment]
I'd prefer to not use the term "defect".  I don't consider myself defective.  I was born with a congenital eye condition -- a congenital visual impairment.

**Comment by awkawk** [comment]
Suggest:
Most low vision is caused by eye diseases and health conditions such as cataracts, glaucoma, and diabetes, which are more common among older people. Some low vision conditions are are present at birth or occur as a result of injury.

**Comment by shawna-slh** [comment]
trying for simpler language:

> Most low vision is caused by eye diseases and health conditions such as cataracts, glaucoma, and diabetes. These are more common among older people. Some low vision is congenital (from birth) and some is caused by injuries.

Not sure if that provides enough emphasis that Denis is looking for with "an increasing number of such conditions are found in seniors, as eye diseases and health conditions become more prevalent as people get older." Perhaps:

> Most low vision is caused by eye diseases and health conditions such as cataracts, glaucoma, and diabetes. These are more common as we age, thus a higher percentage of older people have low vision. Some low vision is congenital (from birth) and some is caused by injuries.

**Comment by shawna-slh** [comment]
Discussed [30 March telecon](https://www.w3.org/2016/03/30-lvtf-minutes.html#item07)
ACTION: Shawn to follow-up with Denis
done: [4 April e-mail](https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0000.html)

**Comment by dboudreau** [comment]
mraccess77 has an excellent point. I would then suggest:

"Most low vision conditions are caused by eye diseases and health conditions such as cataracts, glaucoma, macular degeneration and diabetes. While some low vision conditions are congenital or the result of injuries, an increasing number of such conditions are also found in seniors, as eye diseases and health conditions become more prevalent as people get older."

**Comment by allanj-uaag** [comment]
see comment: https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0002.html

there are a lot of bold statements that would need to be removed or referenced appropriately: 

> o   For example in section 2.3: 'Some causes of low vision can be improved through surgery or medication, and it is not uncommon for someone to have deteriorating vision over several months, and then experience improved vision after treatment.' – this needs a reference or needs to be deleted.
> 
>  Many people with decreased vision due to aging do not consider themselves as having a disability’ –this is a generic statement that may not be true or needs to be supported with a reference.

**Comment by shawna-slh** [comment]
from conversation @dboudreau : OK with RESOLUTION

> Most low vision is caused by eye diseases and health conditions such as cataracts, glaucoma, and diabetes. These are more common among older people. Some low vision is congenital (from birth) and some is caused by injuries.

**Comment by shawna-slh** [comment]
References provided in https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/References -- which is linked from the Introduction.
