### ISSUE TITLE
Scope question

### ISSUE THREAD

**Issue by shawna-slh** [w3c/low-vision-a11y-tf#34]
http://w3c.github.io/low-vision-a11y-tf/requirements.html#scope-of-low-vision

wording from [Introduction](http://w3c.github.io/low-vision-a11y-tf/requirements.html#introduction):

<blockquote>This document, Accessibility Requirements for People with Low Vision, describes what people with low vision need for electronic content, tools, and technologies to be accessible.</blockquote>

The definitions from the impairment side seem clear enough, but there doesn't seem to be a definition of 'electronic content'. Is it intended to cover, for example, content transmitted by communication systems such as Skype (thinking CVAA)? Or video games?

from Ian Hamilton https://lists.w3.org/Archives/Public/public-low-vision-comments/2016JanMar/0002.html

**Comment by mraccess77** [comment]
FWIW The definition of E&IT used in Section 508 from the Clinger-Cohen Act is:

Electronic and information technology.  Includes information technology and any equipment or interconnected system or subsystem of equipment, that is used in the creation, conversion, or duplication of data or information.  The term electronic and information technology includes, but is not limited to, telecommunications products (such as telephones), information kiosks and transaction machines, World Wide Web sites, multimedia, and office equipment such as copiers and fax machines.  The term does not include any equipment that contains embedded information technology that is used as an integral part of the product, but the principal function of which is not the acquisition, storage, manipulation, management, movement, control, display, switching, interchange, transmission, or reception of data or information.  For example, HVAC (heating, ventilation, and air conditioning) equipment such as thermostats or temperature control devices, and medical equipment where information technology is integral to its operation, are not information technology.

**Comment by shawna-slh** [comment]
I'm not inclined to add a definition of "electronic content" &mdash; seems overkill for the purpose of this document. (but open to being talked about of that position :-)

**Comment by shawna-slh** [comment]
LVTF resolved not to add definition of electronic content in [6 April telecon (item 3)](https://www.w3.org/2016/04/06-lvtf-minutes.html#item03)
