### ISSUE TITLE
Update information on acuity

### ISSUE THREAD

**Issue by mraccess77** [w3c/low-vision-a11y-tf#35]
http://w3c.github.io/low-vision-a11y-tf/requirements.html#visacu 

> Visual acuity is the clarity or sharpness of vision. It is generally dependent on the functioning of the retina part of the eye and of the interpretation of the brain. Measurement of distance visual acuity is based on a standard of 20/20 (6/6 in metric).

Acuity can be affected by other things such as Nystagmus (involuntary movement of the eye), cataracts, corneal damage, etc.

> Some low visual acuity can be corrected with glasses, contact lenses, or surgery – and some cannot. Therefore, some people will have blurry vision (low visual acuity) no matter what.

When I have my contacts in -- I am visually impaired but I certainly don't have blurry vision.  My vision lacks detail. When I take my contacts out I have blurry vision.  Blurry vision is caused by a refraction issue -- the way the light hits the retina.  With correction I have no refraction issue but the macula where the fine detail of vision is seen has less sensitivity and thus I don't see those fine details -- but blurry is not an accurate representation of the situation.

**Comment by shawna-slh** [comment]
Re: [Section 2.4.1](http://w3c.github.io/low-vision-a11y-tf/requirements.html#visacu)

In 2.4.2, 2.4.3, and 2.4.4 we don't say what causes it, so I think we should just delete that problem sentence. So the first paragraph would be just:

> Visual acuity is the clarity or sharpness of vision. Measurement of distance visual acuity is based on a standard of 20/20 (6/6 in metric).

I thought about just deleting blurry (so it would be: "Some low visual acuity can be corrected with glasses, contact lenses, or surgery – and some cannot. Therefore, some people will have low visual acuity no matter what.")

However, I think most people will grok "blurry" so much better than just "low visual acuity".

Is it OK as is because it says "**some** people will have blurry vision" (not everyone)???

Maybe we can simply it even more:

> Some low visual acuity can be corrected with glasses, contact lenses, or surgery – and some cannot. Therefore, some people will have blurry vision no matter what.

**Comment by mraccess77** [comment]
I feel blurry is a stereotype of what is often seen by people with low vision and I don't want to perpetuate something that is not totally accurate even if it is common practice.    It is the decrease in detail in many cases.     Also indicating what causes acuity decrease is useful information IMO to leave in.

**Comment by shawna-slh** [comment]
hum. Some people with low vision do describe their vision as blurry, and I'm not sure that's inaccurate for some people. We could cover both like this:

> Some low visual acuity can be corrected with glasses, contact lenses, or surgery – and some cannot. Therefore, some people will have blurry vision or not see fine details no matter what.

What do you think?

Re: listing the causes &mdash; Based on the target audience and the purpose of this document, the Task Force agreed a while ago to put such details in a separate document. Wayne was working on something that I think might provide information such as [this table](http://www.tsbvi.edu/eye-conditions) -- except with conditions, impact on vision, and ICT considerations. He was talking about providing it through a database so it could be presented by conditions or by impact on vision (e.g., visual acuity). Some of his work on this is in [Ontology issue #3](https://github.com/w3c/low-vision-a11y-tf/issues/3) and the [Types of Low Vision wiki page](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Types_of_Low_Vision).

**Comment by mraccess77** [comment]
> Some low visual acuity can be corrected with glasses, contact lenses, or surgery – and some cannot. Therefore, some people will have blurry vision or not see fine details no matter what.

This is better -- I'll just accept that we don't agree as I don't want to hold this up further -- so this change is fine.    

Regarding the term low visual acuity....
I often have people with correctable vision come up to me and say they are legally blind or have low vision (without the glasses) but with the glasses they see within the typical visual acuity range.  They aren't legally blind and they don't have low vision if their vision is correctable.  That is what I believe we are trying to say so we need to make it absolutely clear in this section that if your vision is correctable out of the range of low vision and your fields do not classify you as low vision then that person is not generally seen as having low vision.  We should tie this back to 2.1.

**Comment by WayneEDick** [comment]
Yes, I don't have blurry vision. Not in my head. It's more like small stuff isn't there. 
There are many ways low vision occurs. The retina is one big class, refractive error is another, cloudy fluids are another. So I think editing cause is good. Low visual acuity just means you can't see small stuff.

Wayne

**Comment by shawna-slh** [comment]
For TF input: Suggestion on making this accurate and easy to understand?

> Some low visual acuity can be corrected with glasses, contact lenses, or surgery – and some cannot. Therefore, some people will have blurry vision or not see fine details no matter what.

Is it OK without "blurry"? Maybe:

> Some low visual acuity can be corrected with glasses, contact lenses, or surgery – and some cannot. Therefore, some people will not see small text or fine details no matter what.

Thoughts?

**Comment by mraccess77** [comment]
I like it without the blurry bit.

Jonathan

**Comment by allanj-uaag** [comment]
per minutes https://www.w3.org/2016/04/13-lvtf-minutes.html#item01
requirements.html updated 26 apr 2016

**Comment by allanj-uaag** [comment]
TF member comment, resolved in discussion on telecon. Resolution passed. Marked Reply Sent to indicate issue resolution and documentation.
