### ISSUE TITLE
re-word 3.1.1.

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#38]
Section 3.1.1 – “Some people turn down the brightness of their screen or use an overlay.“ I would suggest, “Some people turn down the brightness of their screen or use an overlay, while others like to increase the brightness especially on mobile devices.” Or something like that.
http://w3c.github.io/low-vision-a11y-tf/requirements.html#text-size

from: https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Mar/0078.html

**Comment by shawna-slh** [comment]
current wording of [3.1.1 Brightness Overall](http://w3c.github.io/low-vision-a11y-tf/requirements.html#brightness-overall)

> Bright light from a screen or other sources prevents some people with low vision (including those with photophobia and with reading disabilities such as dyslexia) from reading and causes pain for some people. Some people turn down the brightness of their screen or use an overlay.

**Question:** Is being able to increase the brightness overall (as opposed to the contrast ratio, which is a separate point addressed elsewhere) an important low vision user need -- more so than for people without low vision? **If yes**, I think we'd want to add something like:

> For other people, it is easier to read with a bright screen, and they sometimes increase the brightness, especially on mobile devices

However, I'm not yet convinced this is an important point to add, and I look forward to additional perspectives.

**Comment by shawna-slh** [comment]
resolved to include it - [6 Apr telecon (item 5)](https://www.w3.org/2016/04/06-lvtf-minutes.html#item05)

**Comment by allanj-uaag** [comment]
https://lists.w3.org/Archives/Public/public-low-vision-comments/2017AprJun/0001.html
