### ISSUE TITLE
Contrast and Brightness

### ISSUE THREAD

**Issue by WayneEDick** [w3c/low-vision-a11y-tf#4]
<article>

<h1>Contrast and Brightness</h1>

<h2>Contrast and Legibility</h2>

<p tabindex="0" >Contrast is the visual effect caused by the difference between the brightness of the foreground and background of a display.  If either region (foreground or background) is bright and the other is dark then we have high contrast.  If the levels of brightness are close like light grey on white, or black on navy blue then the contrast is low. </p>

<p tabindex='0'>Contrast strongly influences the legibility of the text. Legibility is the ease with which letters in text are recognized. With high contrast one can recognize letters easily, with low contrast recognition is difficult. The way one measures legibility is by measuring reading speed and counting errors. If one reads at a rapid rate with few errors then the reader finds the text very legible. Conversely, slow reading with lots of errors implies low legibility. There is a wide range of contrast that enables maximum legibility (reading speed). </p>

<p tabindex="0" >Contrast can be computed using many metrics. The one that matters for accessibility is the contrast ratio L1/L2 where L1 is the brightness (luminance) of the brightest region and L2 is the brightness of the darker region. The precise formula for contrast ratio L1/L2 is complex
    <a href="http://www.w3.org/TR/WCAG20/#contrast-ratiodef">
        [<cite>WCAG Contrast Ratio Definition</cite>]
    </a>,
    but the concept of how contrast ratio is used is easy. Legibility increases with the contrast ratio. </p>

<p tabindex="0" >Everything we have described so far applies to all visual readers, both fully sighted and readers with low vision. However, reduced visual acuity resulting from low vision restricts flexibility considerably.The contrast ratio that supports legibility is much higher for people with reduced acuity. A contrast ratio that is fine for normal readers may reduce legibility below a perceivable level for the reader with reduced visual acuity.</p>

<h2>Brightness, Discomfort and Readability</h2>

<p tabindex='0'>The level of brightness is an issue for almost everyone with low vision.</p>

<p tabindex="0" >Many people with low vision are extremely sensitive to light.  Too much brightness can be accompanied by eye pain and headaches. It is well known that people with albinism have this problem, but few realize that this issue is widespread across the low vision population
    <a href="http://www.tsbvi.edu/eye-conditions">
        [<cite>TBVI, Eye Conditions</cite>]
    </a>.
    Too little brightness is also a  problem. Without sufficient brightness we cannot have the contrast needed for legibility. Reading may be impossible. Many experience blindness in low levels of brightness. Finding a balance is very difficult.</p>

<p tabindex='0'>People with blurred or hazy vision often experience a "halo" effect around letters with too much light. This distraction reduces legibility. Brightness also exacerbates glare an additional distraction. </p>

<p tabindex="0" >Since brightness of foreground or background is necessary for higher contrasts, there is a problem with providing sufficient brightness to support necessary contrast ratios for legibility. In the case of blurred and hazy vision, the halo effect caused by brightness can be mitigated in many cases by using dark background with bright foreground (reverse polarity). For those who have a painful response to bright light, reduced brightness will reduce discomfort but it will also reduced contrast and legibility. This creates an impasse.</p>

<h2>Font-size and Legibility</h2>

<p tabindex="0" >Fortunately contrast is not the only typographic factor to influence legibility. Increasing font size increases legibility, within well defined limits.</p>

```
<p tabindex="0">Given sufficient contrast, the smallest font size a person can read at maximum speed is the critical print size. Newspapers use the average critical print size of normal readers. That saves ink and paper, but the legibility keeps readers buying papers
    <a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3428264/">
        [<cite>Does Print Size Matter for Reading?</cite>]
    </a>.
<p tabindex="0">There is a feasible range of print sizes that support maximum reading speed. A font size in the range is very legible. Anything smaller or larger is not.  </p>
<p tabindex="0">The important thing to note is there is flexibility with font size, just as there is flexibility with contrast.  Many sizes and contrast ratios enable good legibility. That gives us an important trade off.</p>
```

<p tabindex="0" >If we want to use small print (right at the critical print size) we must maintain sufficient contrast, but if we want to have a lower contrast ratio to meet other design goals then the font size must increase to maintain legibility. </p>

<p tabindex='0'>We can see this trade off in print publications. Newspapers choose the critical print size for normal readers to save ink and paper, but keep customers. Fancy hard bound books often use a larger but feasible print size with an off white paper. The combination supports comfortable reading. The contrast ratio may not support optimum legibility at the critical print size, but at a larger font size legibility is preserved. In this case, the need to cut printing cost is less important than providing an inviting environment to read. </p>

```
<p tabindex="0">Increased font size can also improve reading at low contrast ratios for people with reduced acuity and extreme light sensitivity.</p>
```

<h2>Finding an Optimal Balance to Promote Legibility and Readability</h2>

<p tabindex="0">Too much brightness is not really a problem with legibility. People can read rapidly and without error, but still develop eye pain and headaches. The problem of discomfort caused by brightness restricts readability. A person can perceive text very well and still be unable to read long documents because they have painful discomfort. This issue will not be detected by measurement of reading speed.</p>

<p tabindex="0"> This leads us to an open problem. How do we increase legibility and readability at the same time? The problem is not easy. There many trade offs. </p>

<p tabindex="0" >Low contrast can be mitigated by font size, but there are limits to how much font size increase is possible.  The critical font size for a low vision reader is usually much larger than the critical print size for a normal reader.  Moreover, and upper end of the range of feasible sizes for a person with reduced acuity, might be so large that one long word may not fit on a laptop monitor. By adjusting contrast and font size one usually can arrive at a maximum legibility and readability, but the best adjustment is not easy to find and it may sacrifice legibility, readability or both. </p>

<p tabindex="0">There are other factors that influence legibility
    <a href="http://files.eric.ed.gov/fulltext/EJ772089.pdf">
        [<cite>Legibility of typeface for Readers with low vision.</cite>]
    </a>.
    Font face and letter spacing can improve letter and word recognition. Simple font faces tend to promote recognition for people who have difficulty with fine detail. Small increases in letter spacing can also improve letter recognition and reduce reading errors. Increased spacing between lines can also reduce tracking errors, those errors that result from failure to stay on the line being read. </p>

<p tabindex="0">Contrast and brightness are important tools to improve legibility, but they can limit readability by causing discomfort due to extreme light sensitivity. Many typographic factors may mitigate this problem, but finding an optimum balance will vary from individual to individual. </p>

```
</article>
```

**Comment by srinivasuchakravarthula** [comment]
Nice work! Thank you, Wayne. I am not sure if this points is relevant here but I often feel auto change of brightness causes pain to eye to some users. It becomes difficult to have focus on what we are reading when suddenly brightness gets changed. 

Thanks,
Srini

**Comment by JohnRochfordUMMS** [comment]
Hi Wayne,

You make a lot of great points and explain them well. Thank you for your work.

What do you think about replacing:
- "If the levels of brightness are close like light grey on white, or black on navy blue then the contrast is low." with "If the colors of the regions are similar, such as light grey on white, or black on navy blue, then the brightness levels are close and the contrast is low."?
- "normal" with "typical" as the descriptor for readers?

John

**Comment by allanj-uaag** [comment]
+1 to typical

On Mon, Jan 4, 2016 at 9:26 AM, John Rochford notifications@github.com
wrote:

> Hi Wayne,
> 
> You make a lot of great points and explain them well. Thank you for your
> work.
> 
> What do you think about replacing:
> - "If the levels of brightness are close like light grey on white, or
>   black on navy blue then the contrast is low." with "If the colors of the
>   regions are similar, such as light grey on white, or black on navy blue,
>   then the brightness levels are close and the contrast is low."?
> - "normal" with "typical" as the descriptor for readers?
> 
> John
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/low-vision-a11y-tf/issues/4#issuecomment-168705672
> .

## 

Jim Allan, Accessibility Coordinator
Texas School for the Blind and Visually Impaired
1100 W. 45th St., Austin, Texas 78756
voice 512.206.9315    fax: 512.206.9264  http://www.tsbvi.edu/
"We shape our tools and thereafter our tools shape us." McLuhan, 1964

**Comment by WayneEDick** [comment]
That sudden change in brightness is really a problem.  I'm maybe we should
fit it into the discussion of brightness.

Thanks for the comment, Wayne

**Comment by shawna-slh** [comment]
moved to wiki https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Overview_of_Low_Vision#Light_and_Contrast_Sensitivity
