### ISSUE TITLE
3.3.3 - avoid italics

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#41]
Section 3.3.3 – I would suggest adding, “Avoid the use of italics when possible.”
http://w3c.github.io/low-vision-a11y-tf/requirements.html#style

from: https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Mar/0078.html

**Comment by shawna-slh** [comment]
I assume we would include something like that in "best practices"/techniques-type guidance. (but not in this user needs document)

For this user needs doc, perhaps we want to change the order of the explanation text?

Current:

<blockquote>For some people, bold text is easier to read. For some people, it is difficult to read blocks of text that is all underlined or italicized.</blockquote>

Idea:

<blockquote>For some people, it is difficult to read blocks of text that is all italic or underlined. For some people, bold text is easier to read.</blockquote>

I don't feel strongly either way.

**Comment by shawna-slh** [comment]
resolved that initial comment fits in best practice, not user needs - [6 April telecon (after item 7)](https://www.w3.org/2016/04/06-lvtf-minutes.html#item07)

identified that related issues on 3.3.3 Style and 3.5.1 Element-level need refinement

**Comment by allanj-uaag** [comment]
https://lists.w3.org/Archives/Public/public-low-vision-comments/2017AprJun/0001.html
