### ISSUE TITLE
3.5.1 - poor example illustration

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#42]
Section 3.5.1 – The contrast in Fig. 12 is not very good and illustrates a poor example.
http://w3c.github.io/low-vision-a11y-tf/requirements.html#element-level-customization

from Section 3.5.1 – The contrast in Fig. 12 is not very good and illustrates a poor example.

**Comment by shawna-slh** [comment]
from https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Mar/0078.html

**Comment by shawna-slh** [comment]
Figure 12 is based on a **real** user style sheet of a person with low vision (who may wish to identify him/her-self :). It does have a contrast ratio of greater than 4.5:1.

While some people need high contrast, some need lower contrast -- as we say throughout the document (e.g., "an older person might need high contrast but that might be unreadable to a person with light sensitivity").

Note that Section 3.5.1 is on element-level customization, not contrast.

To avoid misunderstandings that the contrast ratio in Fig 12 is good for all, we could add a tweak to the captions. Currently figure captions:

<blockquote>Fig. 12 Web page with user style - with different fonts, indentation, borders, different colors, and dots preceding text to differentiate heading levels</br>Fig. 12 Web page with user style - with different fonts, indentation, borders, different colors, and dots preceding text to differentiate heading levels</blockquote>

Idea for tweaks:

<blockquote>Fig. 12 Web page with user style (moderate contrast) - with different fonts, indentation, borders, different colors, and dots preceding text to differentiate heading levels</br>Fig. 12 Web page with user style (high contrast) - with different fonts, indentation, borders, different colors, and dots preceding text to differentiate heading levels</blockquote>

But does noting the contrast distract from the main point -- the element-level customization?

We could change the user's style sheet for Fig 12 so it is high contrast, but I'm not inclined to do that. For one thing, it would no longer be a real example. Also, I think it's good to show user styles that are different -- it's a real example of what we say throughout the doc...

**Comment by WayneEDick** [comment]
Hi Everyone,
I changed my stylesheet. The one in image 12 was to bright, and the contrast was too much. Now I use this one.
![stylesheet](https://cloud.githubusercontent.com/assets/8195607/14442167/2443f9ce-ffed-11e5-859d-4fb357304a3b.png)
We need an example with lower contrast because many people need that. It really isn't that bad. It's about 5:1.

I don't really get uncomfortable until contrast gets to about 7:1. Note that I use border color and dots to designate headings and levels. I don't waste space with font size.

Wayne

**Comment by allanj-uaag** [comment]
surprisingly the text contrast passes wcag (5.1:1)

On Mon, Apr 11, 2016 at 3:56 PM, WayneEDick notifications@github.com
wrote:

> Hi Everyone,
> I changed my stylesheet. The one in image 12 was to bright, and the
> contrast was too much. Now I use this one.
> [image: stylesheet]
> https://cloud.githubusercontent.com/assets/8195607/14442167/2443f9ce-ffed-11e5-859d-4fb357304a3b.png
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/low-vision-a11y-tf/issues/42#issuecomment-208557667

## 

Jim Allan, Accessibility Coordinator
Texas School for the Blind and Visually Impaired
1100 W. 45th St., Austin, Texas 78756
voice 512.206.9315    fax: 512.206.9264  http://www.tsbvi.edu/
"We shape our tools and thereafter our tools shape us." McLuhan, 1964

**Comment by allanj-uaag** [comment]
We can change the image to reflect the real style sheet in use. 
I think we need to respond to the commenter that as Shawn says...
Figure 12 is based on a real user style sheet of a person with low vision. It does have a contrast ratio of greater than 4.5:1. While some people need high contrast, some need lower contrast -- as we say throughout the document (e.g., "an older person might need high contrast but that might be unreadable to a person with light sensitivity").
The LVTF will leave the image as is.

**Comment by shawna-slh** [comment]
+1 to Jim's resolution about to the commenter.

So the question is do we change the fig captions or not? Or maybe we add a note about it?

**Comment by slhenry** [comment]
Jim in telecon: Add note that these are real styles sheets used by real people. :)

**Comment by allanj-uaag** [comment]
per minutes https://www.w3.org/2016/04/13-lvtf-minutes.html#item02 
commenter replied to https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0004.html
requirements.html updated 26 Apr 2016
