### ISSUE TITLE
figure descriptions

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#43]
Feb 24 we discussed adding longer descriptions to the images. location yet to be determined. I have mined minutes and taken a first pass at the descriptions. 
## Fig. 4.  http://w3c.github.io/low-vision-a11y-tf/requirements.html#color-vision

alt="color wheel with 16 colors"

long description: Color wheel with 12 colors simulating full color perception. Colors, starting at the top of the wheel, are red, red-orange, orange, yellow-orange, yellow, yellow-green, green, blue-green, blue, indigo, purple, purple-red.
## Fig. 5.

alt = "Color wheel simulated view of a person with red-green color blindness, showing reds shifting to green, and green shifting to browns."

long: 12 color wheel simulating red-green color blindness. Colors, starting at the top of the wheel, are yellow-green, yellow-green, yellow-green, yellow-green, yellow, yellow-green, brown, medium-blue, blue, dark-blue, med-blue, green-brown.
## Fig. 6.

alt="Color wheel simulated view of a person with blue-yellow color blindess, showing yellows shifting to pink, and blues shifting to blue-green or browns."

long: 12 color wheel simulating blue-yellow color blindness. Colors, starting at the top of the wheel, are red, red, dark-pink, dark-pink, pink, grey-pink, dark blue-green, blue-green, blue-green, dark-blue-green, olive, dark-red.
## Fig. 7.

alt="Color wheel simulated view of a person with no color perception, showing shades of gray."

long: 12 color wheel simulating no color perception. Colors, starting at the top of the wheel, shades of gray with 4th wedge being the lightest, and 9th wedge being the darkest.
## Fig. 8 http://w3c.github.io/low-vision-a11y-tf/requirements.html#text-contrast
- Background is light-gray
- first heading is largest, sans-serif font, green
- second heading is next largest, sans-serif font, light-green
- text is smallest text, serif font, dark-gray
- third heading is 3rd largest heading, serif font, light green (same color as second heading) 
## Fig. 9
- Background is black
- all headings are the same size and sans-serif font
- first heading is khaki
- second heading is lavender
- text is slightly larger than headings, sans-serif font, light-gray
- third heading is orchid
## Fig. 10.
- Background is black
- all headings are the same size and sans-serif font
- first heading is blue-green
- second heading is yellow
- text is slightly larger than headings, sans-serif font, light-gray
- third heading is blue
## Fig. 11  http://w3c.github.io/low-vision-a11y-tf/requirements.html#element-level-customization
- Background is white
- first heading is largest, sans-serif font, dark-green
- second heading is next largest, sans-serif font, green
- text is smallest text, serif font, dark-gray
- third heading is 3rd largest heading, serif font, green (same color as second heading) 
- link is serif font, blue, underlined
- bold is bold serif text
- italic is italic serif text
- bullet items are indented 3 spaces, filled circle dot vertically centered (1/3 size text font size), one space, item text
## Fig. 12
- Background is khaki
- all text including headings is the same size
- first heading is sans-serif font, maroon text and full border around element, 1 period with a space (. ) precedes text of heading, period and text indented 2 spaces from border
- second heading is sans-serif font, blue text and border around element, 2 periods with a space (.. ) precedes text of heading, periods and text indented 2 spaces from border
- text is larger than headings, serif font, black text, gray border around element, text not indented
- third heading is 3rd largest heading, serif font, purple text and border around element, 3 periods with a space (... ) precedes text of heading, periods and text indented 2 spaces from border
- link is serif font, brown, underlined, surrounded by square brackets [ ]
- bold is bold serif text
- italic is italic serif text
- bullet items are indented one space, the list has a left margin border of light blue, each item has a top border of lavender 
## Fig. 13
- Background is black 
- all headings are sans-serif font, spring green
- first heading is largest text, indented 2 spaces from left margin
- second heading is next largest text, indented 4 spaces from left margin
- text is smallest text on page, serif font, white 
- third heading is 3rd largest heading, indented 6 spaces from left margin
- link is serif font, blue, underlined, surrounded by square brackets [ ]
- bold is bold serif text, yellow
- italic is italic serif text, pale yellow
- bullet items indented 1 space, horizontally centered bullet, one space, text

**Comment by lauracarlson** [comment]
Perhaps consider tweaking the color wheel `longdesc`s to provide a bit more orientation, stucture, and detail. [Jeanne created nice table](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Color-Blindness-Table) that provides the big picture and good structure. It could be broken down into a 2 column table for each wheel or we could use a list to provide the structure. For example:

## Figure 4 `longdesc`

> This illustration is a color wheel with 12 wedges simulating full color perception. Colors, starting at the 12 o'clock position and proceeding clockwise around the wheel are:
> -   12:00 = red
> -   1:00 = red-orange
> -   2:00 = orange
> -   3:00 = yellow-orange
> -   4:00 = yellow
> -   5:00 = yellow-green
> -   6:00 = green
> -   7:00 = blue-green
> -   8:00 = blue
> -   9:00 = indigo
> -   10:00 = purple
> -   11:00 = purple-red

or the list could be a table instead:

> <table border="1">
> <tbody>
> <tr>
> <th>Position on Color Wheel</th>
> <th>**Full Color perception**</th>
> </tr>
> <tr>
> <td>12:00</td>
> <td>Red</td>
> </tr>
> <tr>
> <td>1:00</td>
> <td>Red-orange</td>
> </tr>
> <tr>
> <td>2:00</td>
> <td>Orange</td>
> </tr>
> <tr>
> <td>3:00</td>
> <td>Orange-yellow</td>
> </tr>
> <tr>
> <td>4:00</td>
> <td>Yellow</td>
> </tr>
> <tr>
> <td>5:00</td>
> <td>Yellow-green</td>
> </tr>
> <tr>
> <td>6:00</td>
> <td>Green</td>
> </tr>
> <tr>
> <td>7:00</td>
> <td>Green-blue</td>
> </tr>
> <tr>
> <td>8:00</td>
> <td>Blue</td>
> </tr>
> <tr>
> <td>9:00</td>
> <td>Blue-purple</td>
> </tr>
> <tr>
> <td>10:00</td>
> <td>Purple</td>
> </tr>
> <tr>
> <td>11:00</td>
> <td>Purple-red</td>
> </tr>
> </tbody>
> </table>

**Comment by lauracarlson** [comment]
For a `longdesc` of the Figure 7 [achromatopsia.png](https://www.w3.org/TR/low-vision-needs/images/achromatopsia.png), [LAB Color space](https://en.wikipedia.org/wiki/Lab_color_space) provides a L (lightness or luminous level) where #ffffff in Hex (white) is equal to a 100 lightness value and #000000 in Hex (black) is equal to a 0 lightness value. So the following provides a HEX to L-A-B conversion for the achromatopsia image from Jeanne's table:
-   #828282 = 54-0-0
-   #8e8e8e = 59-0-0
-   #a8a8a8 = 69-0-0
-   #bcbcbc = 76-0-0
-   #eeeeee = 94-0-0
-   #b8b8b8 = 75-0-0
-   #7d7d7d = 52-0-0
-   #737373 = 48-0-0
-   #4c4c4c = 33-0-0
-   #333333 = 21-0-0
-   #505050 = 34-0-0
-   #636363 = 42-0-0

If we want to provide more detail and structure for the Figure 7 `longdesc,` we could consider something such as the following:

> This illustration is a simulation of no color perception of the 12-wedge full color wheel. All wedges are gray and vary in lightness values. The lightest wedge is in the 4 o'clock position. The darkest wedge is in the 9 o'clock position.
> 
> All values, starting at the 12 o'clock position and proceeding clockwise around the wheel are follows.
> 
> <table border="1">
> <tbody>
> <tr>
> <th>Position on Wheel</th>
> <th>
>  Lightness  Value in  LAB color space
> </th>
> </tr>
> <tr>
> <td>12:00</td>
> <td>54</td>
> </tr>
> <tr>
> <td>1:00</td>
> <td>59</td>
> </tr>
> <tr>
> <td>2:00</td>
> <td>69</td>
> </tr>
> <tr>
> <td>3:00</td>
> <td>76</td>
> </tr>
> <tr>
> <td>4:00</td>
> <td>94</td>
> </tr>
> <tr>
> <td>5:00</td>
> <td>75</td>
> </tr>
> <tr>
> <td>6:00</td>
> <td>52</td>
> </tr>
> <tr>
> <td>7:00</td>
> <td>48</td>
> </tr>
> <tr>
> <td>8:00</td>
> <td>33</td>
> </tr>
> <tr>
> <td>9:00</td>
> <td>21</td>
> </tr>
> <tr>
> <td>10:00</td>
> <td>34</td>
> </tr>
> <tr>
> <td>11:00</td>
> <td>42</td>
> </tr>
> </tbody>
> </table>

**Comment by shawna-slh** [comment]
I am missing the value of such detailed information, especially for the color wheels. It seems like unnecessary complexity. **What do users who do not see the image (well or at all) need to know - or even want to know?** It seems like what we have in the alt for the color wheels is all the information a person would want to know (although it could be edited a bit to be a little more clear and possible a tiny bit more descriptive -- but _without _adding much more detail or more words).

**Comment by lauracarlson** [comment]
Hi Shawn,
Long text alternatives can provide for rich, expressive documentation of a visual image and should be used when alt is insufficient to embody the visual qualities of an image.

To help decide whether a long text alternative is necessary turn off images in your browser and ask yourself, "Does the short text alternative convey the information and meaning present in the image?"
- If the answer is yes, a long text alternative is not needed.
- If the answer is no, a long text alternative is needed.

I believe that for the examples that descriptions have been written, the answer is no.

Long descriptions provide _user choice_. Screen readers read out the value of an alt attribute automatically. The old saying goes "a picture is worth a thousand words". While this is true, that doesn't mean everyone wants to hear all one thousand words at once or at this particular moment. 

In contrast a long description provides the ability to pause, step outside of the page flow to obtain a description of a complex image. The difference is akin to glancing at a complex chart or diagram (alt functionality) versus studying it (long description functionality). Sighted users, have that choice (to glance or study). Long text alternatives offer that choice to people with disabilities. Some people born blind may not be interested in what such an image looks like. If they don’t want read a long description, they won’t. But other people who have not been born blind, may very well want a long description. Offering long descriptions provide user choice.

In addition, long descriptions _facilitate communication_ between people without disabilities and people with disabilities. For instance, if a sighted person comments on how a certain color is perceived differently among the 4 color wheels, a person with visual disabilities would be able to track exactly what is meant if we provided [Jeanne's table](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Color-Blindness-Table).

**Comment by allanj-uaag** [comment]
+1 to Laura. We started this conversation at a call a month ago. We
discussed describing the images so all would know exactly what the images
are trying to convey. Also, eating our own dog food - adding alt and some
form of long description to images in a mostly technical document. We have
the descriptions...just need to decide how to integrate them in the
document.

On Tue, Apr 12, 2016 at 3:57 PM, Laura Carlson notifications@github.com
wrote:

> Hi Shawn,
> Long text alternatives can provide for rich, expressive documentation of a
> visual image and should be used when alt is insufficient to embody the
> visual qualities of an image.
> 
> To help decide whether a long text alternative is necessary turn off
> images in your browser and ask yourself, "Does the short text alternative
> convey the information and meaning present in the image?"
> - If the answer is yes, a long text alternative is not needed.
> - If the answer is no, a long text alternative is needed.
> 
> I believe that for the examples that descriptions have been written, the
> answer is no.
> 
> Long descriptions provide _user choice_. Screen readers read out the
> value of an alt attribute automatically. The old saying goes "a picture is
> worth a thousand words". While this is true, that doesn't mean everyone
> wants to hear all one thousand words at once or at this particular moment.
> 
> In contrast a long description provides the ability to pause, step outside
> of the page flow to obtain a description of a complex image. The difference
> is akin to glancing at a complex chart or diagram (alt functionality)
> versus studying it (long description functionality). Sighted users, have
> that choice (to glance or study). Long text alternatives offer that choice
> to people with disabilities. Some people born blind may not be interested
> in what such an image looks like. If they don’t want read a long
> description, they won’t. But other people who have not been born blind, may
> very well want a long description. Offering long descriptions provide user
> choice.
> 
> In addition, long descriptions _facilitate communication_ between people
> without disabilities and people with disabilities. For instance, if a
> sighted person comments on how a certain color is perceived differently
> among the 4 color wheels, a person with visual disabilities would be able
> to track exactly what is meant if we provided Jeanne's table
> https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Color-Blindness-Table.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/low-vision-a11y-tf/issues/43#issuecomment-209098868

## 

Jim Allan, Accessibility Coordinator
Texas School for the Blind and Visually Impaired
1100 W. 45th St., Austin, Texas 78756
voice 512.206.9315    fax: 512.206.9264  http://www.tsbvi.edu/
"We shape our tools and thereafter our tools shape us." McLuhan, 1964

**Comment by allanj-uaag** [comment]
appendix created http://w3c.github.io/low-vision-a11y-tf/Appendix-Image-Descriptions.html
