### ISSUE TITLE
Note to tool developers not a user need - delete or edit?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/low-vision-a11y-tf#45]
In reviewing https://github.com/w3c/low-vision-a11y-tf/issues/40, I noted that [3.3.2 Font](http://w3c.github.io/low-vision-a11y-tf/requirements.html#font) includes:

> Note to tool developers: When providing users a list of fonts to choose from, present the font name in the font itself — e.g., Times, Veranda, Courier — so users can tell what each font looks like before choosing it.

That is not written as a user need. So we either need to deleted it or edit it. Perhaps something along the lines of:

<blockquote>It is easier to pick more readable fonts if in lists of fonts, the font name is in the font itself — e.g., Times, Veranda, Courier — so users can see what each font looks like before choosing it.</blockquote>

_(above could use wordsmithing!)_

This is not an absolute user need -- but sure improves usability significantly -- and somewhat more so for people with low vision than not.

Edit or delete???

**Comment by allanj-uaag** [comment]
edit.
perphaps

> It is easier to pick more readable fonts if each font name in the list is in its font — e.g., Times, Veranda, Courier (these should be in their font to illustrate) — so users can see how each font looks before choosing it.

**Comment by shawna-slh** [comment]
updated per [13 April 2016 minutes](https://www.w3.org/2016/04/13-lvtf-minutes.html#item04)
