### ISSUE TITLE
italics, bold, underline

### ISSUE THREAD

**Issue by shawna-slh** [w3c/low-vision-a11y-tf#50]
From [6 April telecon (after item 7)](https://www.w3.org/2016/04/06-lvtf-minutes.html#item07) (spurred by Issue https://github.com/w3c/low-vision-a11y-tf/issues/41)

We need to rethink this issue overall, including what we say in
- [3.3.3 Style](http://w3c.github.io/low-vision-a11y-tf/requirements.html#style)
- [3.5.1 Element-level Customization](http://w3c.github.io/low-vision-a11y-tf/requirements.html#element-level-customization)

**Comment by allanj-uaag** [comment]
from: https://lists.w3.org/Archives/Public/public-low-vision-comments/2016JanMar/0005.html

Would it be useful to include the option of setting the colour of links / interactive text? These may not be discernable if their colour cannot be adapted to chosen bg colour,

Similar to Issue [#53](https://github.com/w3c/low-vision-a11y-tf/issues/53)

**Comment by allanj-uaag** [comment]
​from: https://lists.w3.org/Archives/Public/public-low-vision-comments/2016JanMar/0005.html

 "Users can change the font face (also called font family or typeface) of  all text"
"Users can change the text style (underline, italic, bold) of blocks of text."

Again, my context is mobile use, and the issue is related to the above - some fonts are wider so on controls they might either lead to cut-off text or wrapping and displacement of controls. Similar exception?

One particular thing that I found missing is the ability to customise grids and leading lines. In our tests with low vision users, we often had the issue that light grey grids weren't perceived and items not allocated accordingly.Say, in a Samsung calendar grid, the salient info can easily be allocated to the wrong day (see Fig 10 in http://www.incobs.de/tests/items/tablet-tests-mit-sehbehinderten-nutzern-gebrauchstauglichkeit.html)

A similar issue is controls that have a large offset from the label.  Moving the visible section (e.g. on a mobile device) to bring related control or label in view is much harder if there is no visible guiding line helping in making the link (e.g. (on Windows Mobile). Web  / App developers may be required to ensure 4.5:1  contrast of leading lines / grids where these aid perception/navigation (this could presumably also be a system-level setting where contrast of grids and dividing / leading lines can be increased).

**Comment by WayneEDick** [comment]
Visual semantics are important for reading. Italics are not a good way to implement visual semantics for some users but they are good for understanding the context of text.  
How can this be addressed. 
There are a few ways:
Each time italics are encountered replace them with another typographic choice. I just substitute the italics wit "Comic Sans MS". Its curvy and with vertical space. The curvy of italic doesn't both it is the slanting of the white space.
Here are the needs:
1) Users need to avoid styles with known problems like italics. We should discourage the use of italics for decoration. 
2) Users need typographic changes to recognize a change in semnatic context for a region of text. That is they need the same functionality italics use when they convey meaning.

**Comment by allanj-uaag** [comment]
We already have 3.3.2 "Need to change font " , 3.1.3 Color, and 3.5.1 ability to configure elements. we can tell the author to avoid italics (or whatever). However, it would be better to allow the user to control what is displayed. We have many granular requirements. The document when taken as a whole says (to me) that the user needs to be able to control/configure/override the web content displayed. Italic, visited and unvisited link color, and other issues are even more granular. Do they need to be called out? Perhaps. In techniques or introductory material. I don't think they need a requirement. They seem to be covered by 3.1.3, 3.3.2, and 3.5.1.

**Comment by shawna-slh** [comment]
Currently:

> 3.3.3 Style
> For some people, it is difficult to read blocks of text that is all italicized or underlined. For some people, bold text is easier to read.
> User Need - Style: Users can change the text style (underline, italic, bold) of blocks of text.

Suggest: Add definition of "blocks of text" (from WCAG). Add note something like "(This applies to blocks of text, not individual words or phrases.)":

> 3.3.3 Style
> For some people, it is difficult to read blocks of text [link to def] that is all italicized or underlined. For some people, bold text is easier to read. (This applies to blocks of text, not individual words or phrases.)
> User Need - Style: Users can change the text style (underline, italic, bold) of blocks of text.

Currently:

> 3.5.1 Element-level Customization
> Some people change the way certain elements are displayed to make it easier to distinguish types of text, such as headings. If all text is increased proportionally, headings can become very large and bigger than people need to read the main body text. So some people prefer for headings to be smaller and they use styling such as font, color, and indentation to distinguish heading levels.

Suggest: Expand this to clearly cover things like links, em, strong, etc.

Thoughts on how we want to expand this? Ideas for wording?

**Comment by lauracarlson** [comment]
For 3.5.1 Element-level Customization, maybe consider adding something like the following after "Some people change the way certain elements are displayed to make it easier to distinguish types of text." and before the "If all text is increased proportionally..." bit that details how headings can be customized.

> When markup is used according to specification, it provides semantic meaning. This in turn helps a person set a customized visual presentation for headings and links, as well as `<strong>`, `<em>`, `<cite>`, and other elements.

**Comment by allanj-uaag** [comment]
merged Shawn and Laura

> 3.5.1 Element-level Customization
> Some people change the way certain elements are displayed to make it easier to distinguish types of text, such as headings. When markup is used according to specification, it provides semantic meaning. This in turn helps a person set a customized visual presentation for headings and links, as well as <strong>, <em>, <cite>, and other elements. If all text is increased proportionally, headings can become very large and bigger than people need to read the main body text. So some people prefer for headings to be smaller and they use styling such as font, color, and indentation to distinguish heading levels.

Perhaps change the last sentence to be 

> So some people prefer for headings to be the same size as paragraph text. They use styling such as font, color, and indentation to distinguish heading levels and other semantics.

**Comment by allanj-uaag** [comment]
resolution https://www.w3.org/2016/04/20-lvtf-minutes.html#item03

**Comment by allanj-uaag** [comment]
new wording 
3.3.3 For some people, it is difficult to read blocks of text [link to def] that is all italicized or underlined. For some people, substituting bold text or a different font for italics is easier to read. This applies to blocks of text, not individual words or phrases.

**Comment by shawna-slh** [comment]
Sorry I missed the meeting where this was discussed. For 3.3.3, I think we want to keep it simple and follow the pattern that we have throughout that section &mdash; that is, the first two sentences explain the reason behind user need &mdash; and not add information about "substituting" style or using different font for italics. I think that applies more to Element-level Customization, and I suggest we add a pointer to that. So I propose we leave the first part as is, and add a second paragraph:

> [3.3.3 Style](http://w3c.github.io/low-vision-a11y-tf/requirements.html#style)
> For some people, it is difficult to read text that is all italicized or underlined. For some people, bold text is easier to read. 
> 
> This user need applies to [blocks of text](http://w3c.github.io/low-vision-a11y-tf/requirements.html#blockstextdef), not individual words or phrases. A related user need is [Element-level Customization](http://w3c.github.io/low-vision-a11y-tf/requirements.html#element-level-customization).
> 
> User Need - Style: Users can change the text style (underline, italic, bold) of blocks of text.

**Comment by shawna-slh** [comment]
For [3.5.1 Element-level Customization](http://w3c.github.io/low-vision-a11y-tf/requirements.html#element-level-customization), there are several issues here and I think we want to address them in separate paragraphs. Proposal:

> Some people change the way certain elements are displayed to make it easier to read and to distinguish types of text, such as headings, lists, links, strong, em, cite, etc.
> 
> Headings: If all text is increased proportionally, headings can become very large and bigger than people need to read the main body text. Some people prefer for headings to be smaller, and they use settings such as font, color, and indentation to distinguish heading levels.
> 
> Style: As stated in 3.3.3 Style, for some people it is difficult to read text that is all italicized or underlined, and for some bold text is easier to read. In addition to overall changes, some people need to make element-level changes. For example, a person might set all text to bold, and then for text that is marked up to be bold they use different settings such as font or color to distinguish it.
> 
> For this to work, content needs to be marked up appropriately based on semantic meaning.
> 
> The images below show example web content dispayed with real user style sheets using element-level customization.

**Comment by lauracarlson** [comment]
Agree with Shawn's approach. 

Suggest replacing "semantic meaning" as it seems redundant. Something such as "semantic structure" may be more accurate.

**Comment by shawna-slh** [comment]
+1 to Laura "semantic meaning" -> "semantic structure"
Resolution in 2 June 2016 telecon

**Comment by shawna-slh** [comment]
Done. (will upload updated version soon)

**Comment by allanj-uaag** [comment]
added statements  to ​Australian Blindness Forum (ABF) comment. waiting for other issues to be closed to complete the reply.

**Comment by allanj-uaag** [comment]
https://lists.w3.org/Archives/Public/public-low-vision-comments/2017AprJun/0002.html
