### ISSUE TITLE
expanding list for 3.5.1?

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#53]
from https://lists.w3.org/Archives/Public/public-low-vision-comments/2016JanMar/0005.html
​
 Contrast
" User Need - Contrast: Users can set the background color and the text color from the full color spectrum."

Would it be useful to include the option of setting the colour of links / interactive text? These may not be discernable if their colour cannot be adapted to chosen bg colour,

**Comment by shawna-slh** [comment]
subsumed by #50

**Comment by allanj-uaag** [comment]
https://lists.w3.org/Archives/Public/public-low-vision-comments/2017AprJun/0002.html
