### ISSUE TITLE
cut-off text

### ISSUE THREAD

**Issue by shawna-slh** [w3c/low-vision-a11y-tf#55]
​from: https://lists.w3.org/Archives/Public/public-low-vision-comments/2016JanMar/0005.html

"Users can change the font face (also called font family or typeface) of all text"
"Users can change the text style (underline, italic, bold) of blocks of text."

Again, my context is mobile use, and the issue is related to the above - some fonts are wider so on controls they might either lead to cut-off text or wrapping and displacement of controls. Similar exception?

**Comment by shawna-slh** [comment]
I think this is addressed by [3.7.1 Seeing All Interface Elements](http://w3c.github.io/low-vision-a11y-tf/requirements.html#seeing-all-interface-elements)

**Comment by allanj-uaag** [comment]
agree

**Comment by allanj-uaag** [comment]
https://lists.w3.org/Archives/Public/public-low-vision-comments/2017AprJun/0002.html
