### ISSUE TITLE
space between control and label

### ISSUE THREAD

**Issue by shawna-slh** [w3c/low-vision-a11y-tf#56]
​from: https://lists.w3.org/Archives/Public/public-low-vision-comments/2016JanMar/0005.html

A similar issue is controls that have a large offset from the label. Moving the visible section (e.g. on a mobile device) to bring related control or label in view is much harder if there is no visible guiding line helping in making the link (e.g. (on Windows Mobile). Web / App developers may be required to ensure 4.5:1 contrast of leading lines / grids where these aid perception/navigation (this could presumably also be a system-level setting where contrast of grids and dividing / leading lines can be increased).

**Comment by shawna-slh** [comment]
Should be covered in [3.6.2 Proximity of Related Information](http://w3c.github.io/low-vision-a11y-tf/requirements.html#proximity-of-related-information)

**Comment by allanj-uaag** [comment]
agree

**Comment by allanj-uaag** [comment]
https://lists.w3.org/Archives/Public/public-low-vision-comments/2017AprJun/0002.html
