### ISSUE TITLE
Section 2.1 : Definition of low vison

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#62]
from https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0003.html
[Section 2.1](http://w3c.github.io/low-vision-a11y-tf/requirements.html#scope-of-low-vision)

·         Need more precise definition of low vision.  The current definition is not very clear and does not refer to the fact that both eyes are affected when a person is considered to have low vision. Please see some reference material to assist with a more precise definition of low vision at the end of this email.*

*Low Vision definition

Low Vision

·         Low vision may be due to reduced visual acuity (VA) and, or reduced visual field (VF). The classification of low vision includes moderate and severe vision impairment and is thus used in the presence of visual acuity worse than 6/18 but equal to or better than 3/60, with both eyes open or the better eye, with presenting glasses or contact lenses, and in the presence of a permanent condition (Australian Government Department of Health and Ageing, 2013; World Health Organisation [WHO], 2010). Therefore children with low vision have a range of residual vision and may use a combination of magnification tools, including larger print, optical and electronic magnification aids and decreased working distance, to enable them to access printed information, such as worksheets or examinations (Farmer & Morse, 2007; Lueck, Bailey, Greer, Tuan, Bailey & Dornbusch, 2003). Children with low vision will experience difficulties when accessing visual information if they lack the appropriate tools that aid efficient use of residual vision (Lueck, Bailey, Greer, Tuan, Bailey & Dornbusch, 2003; Farmer & Morse, 2007).

·         “Low Vision – to be used for lesser degrees of vision loss, where individuals can be helped significantly by vision enhancement aids and devices”. Referenced on page 2 of the Colenbrander resource attached.

·         “The term "low vision" included in the previous revision has been replaced by categories 1 and 2 to avoid confusion with those requiring low vision care”. From the table below, it indicates that low vision is used to describe visual acuity between the range of 6/18 to 3/60. (Referenced in section H54.9 in the link below which is titled International Statistical Classification of Diseases and Related Health Problems 10th Revision (ICD-10)-WHO Version for ;2016 http://apps.who.int/classifications/icd10/browse/2016/en#/H53-H54)

**Comment by allanj-uaag** [comment]
from https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0002.html

[2.1 Scope of Low Vision](http://w3c.github.io/low-vision-a11y-tf/requirements.html#scope-of-low-vision)
current wording -
“In considering user needs, this document uses a broad scope of low vision to include all visual impairments except significant blindness — including impairments from aging, “color blindness”, and impairments that are often categorized as legally blind yet people have sufficient vision to see user interfaces in some situations.”

proposal  “… people have sufficient vision to recognize display informations with adequate visual frameworks.”

@@ seems a translation issue from german

**Comment by shawna-slh** [comment]
ACTIONS from [26 May 2016](https://www.w3.org/2016/05/26-lvtf-minutes.html#item07):
- Wordsmith "user interfaces" out
- To: "In some contexts, such as social program benefits, people are classified as having low vision or being “legally blind”." add other I18N terms as appropriate.

**Comment by allanj-uaag** [comment]
https://www.w3.org/2016/05/26-lvtf-minutes.html#item07

**Comment by allanj-uaag** [comment]
lvtf-action-58  ACTION: jim to write disclaimer (last para of intro) that we are general [recorded in http://www.w3.org/2016/05/26-lvtf-minutes.html#action02]

**Comment by shawna-slh** [comment]
To "Wordsmith "user interfaces" out",
Changed
> ... often categorized as legally blind yet people have sufficient vision to see user interfaces in some situations

to 
> ... often categorized as legally blind yet people have sufficient vision to see information in some situations

and changed:
> Thus users need to be able to adjust user interfaces to meet their needs.

to:
> Thus users need to be able to adjust information display to meet their needs

**Comment by shawna-slh** [comment]
To address ""In some contexts, such as social program benefits, people are classified as having low vision or being “legally blind”." add other I18N terms as appropriate."

* We already have:
> “Low vision” refers to visual impairments other than blindness. Other terms, such as “partially sighted” and “sight impaired”, are used in different contexts.

* To:
> In some contexts, such as social program benefits, people are classified as having low vision or being “legally blind”.

added:
> ... low vision **or** being “legally blind” (“severely sight impaired” or other terms)

**Comment by shawna-slh** [comment]
I think this issue is all addressed, so I closed it.
