### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#63]
from https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0002.html

Is there a reason, why you don’t mention recommendations for the design of Photos? For diagrams and similar graphics you can apply many of the themes relevant for text (font, contrast, …). But there are some things that make photos easier to see:

• Choose your segment well! If you want to portrait a person, make a head shot and not a picture of the person walking to his or her office.
• Take care of good contrast on your photo! In times of black and white photography lightning, dressing and lipstick were applied very carefully.
• Offer relevant photos in HD by clicking on “View photo on full screen”.

**Comment by shawna-slh** [comment]
From [26 May 2016 minutes](http://www.w3.org/2016/05/26-lvtf-minutes.html) - to existing User Need that people can get important info from images, include photos

Probably related to [action-43](https://www.w3.org/WAI/GL/low-vision-a11y-tf/track/actions/43)

**Comment by allanj-uaag** [comment]
https://www.w3.org/2016/05/26-lvtf-minutes.html#resolution01

**Comment by shawna-slh** [comment]
Specific guidance for taking photos is outside the scope of this document.

General contrast issue is being addressed in [Issue 54](https://github.com/w3c/low-vision-a11y-tf/issues/54)
