### ISSUE TITLE
Editorial: Electronic vs Digital content

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#66]
from: https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0002.html

> ​
> Is there a reason, why you use the term “electronic content” and not “digital content“? Spontaneously I associate hardware with the term “electronic”, while the document is all about software.

**Comment by lauracarlson** [comment]
Changing it to "Web content" may be more accurate.

**Comment by shawna-slh** [comment]
While some of the future work may be confined to web content, we previously discussed that we want this document to be broader that web content. (/me can try to dig up minutes if needed...)

I'm not coming up with clear points for or against "electronic content" vs. "digital content"....

**Comment by allanj-uaag** [comment]
from Andrew
This is a common term. “Electronic and Information Technology” is a very common phrase.

**Comment by lauracarlson** [comment]
Electronic and Information Technology (EIT) is used in requirements, such as Section 508.

**Comment by shawna-slh** [comment]
+1 for leaving it "...electronic content, tools, and technologies to be accessible"

**Comment by allanj-uaag** [comment]
+1 to leaving it "electronic content, tools, and technologies to be
accessible"

On Thu, Jun 2, 2016 at 6:57 AM, shawn_slh notifications@github.com wrote:

> +1 for leaving it "electronic content, tools, and technologies to be
> accessible"
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/low-vision-a11y-tf/issues/66#issuecomment-223270458,
> or mute the thread
> https://github.com/notifications/unsubscribe/AG_WL4-PXtsq6FbgxPHgC1YMEtM9EQ7tks5qHsVBgaJpZM4Ikmza
> .

## 

Jim Allan, Accessibility Coordinator
Texas School for the Blind and Visually Impaired
1100 W. 45th St., Austin, Texas 78756
voice 512.206.9315    fax: 512.206.9264  http://www.tsbvi.edu/
"We shape our tools and thereafter our tools shape us." McLuhan, 1964
