### ISSUE TITLE
Disclaimer draft (action-58)

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#67]
lvtf-ACTION-58: Write disclaimer (last para of intro) that we are general
 https://www.w3.org/WAI/GL/low-vision-a11y-tf/track/actions/58
related to Issue 62 https://github.com/w3c/low-vision-a11y-tf/issues/62

current wording: 
This document is intended to provide the background for developing guidance on making web content, tools, and technologies accessible to people with low vision.

Proposed wording:
This document is intended to provide the background for developing guidance on making web content, tools, and technologies accessible to people with low vision. As a guidance document for developers and tool makers, it is very general. It is not intended, nor does it need to be scholarly. As an "informative" document, terms are localized to the US. (@@add alternative terms in the References). The taskforce decided that creating definitions which encompass regional, national, and international definitions is not possible. We do not define many terms. Rather, we provide a conceptual framework for developers and tool makers to understand "low vision" and the user needs.

**Comment by lauracarlson** [comment]
Hi Jim,

That is what we need to explain alright. Perhaps consider saying the doc is "general by design" and specific terms are "beyond its scope"? Would something such as the following help clarify?

> This document is intended to provide the background for developing guidance on making web content, tools, and technologies accessible to people with low vision. As an [informative](https://www.w3.org/TR/WCAG20/#informativedef) document for developers and tool makers, it is general by design. It is not intended, nor does it need to be scholarly. Terms are localized to the US. (@@add alternative terms in the References). Definitions of regional, national, and international terms are beyond the scope of this document. It defines few terms. Rather, it provides a conceptual framework for developers and tool makers to understand "low vision" and the user needs.

**Comment by allanj-uaag** [comment]
Thanks Laura.
Like the word choice. Much cleaner.

On Tue, May 31, 2016 at 12:06 PM, Laura Carlson notifications@github.com
wrote:

> Hi Jim,
> 
> That is what we need to explain alright. Perhaps consider saying the doc
> is "general by design" and specific terms are "beyond its scope"? Would
> something such as the following help clarify?
> 
> This document is intended to provide the background for developing
> guidance on making web content, tools, and technologies accessible to
> people with low vision. As an informative
> https://www.w3.org/TR/WCAG20/#informativedef document for developers
> and tool makers, it is general by design. It is not intended, nor does it
> need to be scholarly. Terms are localized to the US. (@@add
> https://github.com/add alternative terms in the References).
> Definitions of regional, national, and international terms are beyond the
> scope of this document. It defines few terms. Rather, it provides a
> conceptual framework for developers and tool makers to understand "low
> vision" and the user needs.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/low-vision-a11y-tf/issues/67#issuecomment-222753900,
> or mute the thread
> https://github.com/notifications/unsubscribe/AG_WLx0Z7rf-xtxi5kSEkhGapfGLqqbvks5qHGqDgaJpZM4Iqsdi
> .

## 

Jim Allan, Accessibility Coordinator
Texas School for the Blind and Visually Impaired
1100 W. 45th St., Austin, Texas 78756
voice 512.206.9315    fax: 512.206.9264  http://www.tsbvi.edu/
"We shape our tools and thereafter our tools shape us." McLuhan, 1964

**Comment by shawna-slh** [comment]
Good ideas Jim & Laura!

I think the "disclaimer" aspect is mostly related to the information in the Overview of Low Vision section, and not the User Needs section. I think it would weaken the User Needs section if we put such a disclaimer in the Introduction. Therefore, I propose we put it in the Overview of Low Vision section.

The document currently includes some terms beyond the US, and I don't think we need or want to limit it to US-localized terms.

Personally, I _really_ like the wording "it provides a conceptual framework" – however, I wonder if we want to use simpler wording. 

How about something simple like this for a short paragraph right under the [h2] [Overview of Low Vision](http://w3c.github.io/low-vision-a11y-tf/requirements.html#overview-of-low-vision)?:

> This section provides basic information about low vision related to information and communication technologies. It is not intended to provide formal definitions of terms. It is intended to provide background information for understanding user experiences and user needs.

**Comment by lauracarlson** [comment]
Brilliant. I think you nailed it, Shawn.

**Comment by allanj-uaag** [comment]
works for me. good simplification/tersification

On Thu, Jun 9, 2016 at 6:30 AM, Laura Carlson notifications@github.com
wrote:

> Brilliant. I think you nailed it, Shawn.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/low-vision-a11y-tf/issues/67#issuecomment-224868864,
> or mute the thread
> https://github.com/notifications/unsubscribe/AG_WL4WDTTs8i4kKRYU4fO40cUa82E1Fks5qJ_lmgaJpZM4Iqsdi
> .

## 

Jim Allan, Accessibility Coordinator
Texas School for the Blind and Visually Impaired
1100 W. 45th St., Austin, Texas 78756
voice 512.206.9315    fax: 512.206.9264  http://www.tsbvi.edu/
"We shape our tools and thereafter our tools shape us." McLuhan, 1964

**Comment by shawna-slh** [comment]
RESOLVED 9 June 2016 telecon

**Comment by shawna-slh** [comment]
done. (will upload later today)
