### ISSUE TITLE
Split from #61 Section 2.4 language

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#68]
#61

from https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0003.html
[Section 2.4](https://github.com/w3c/low-vision-a11y-tf/issues/68)
· Should say factors that impact on visual functioning rather than categories of visual impairment.
· Replace ‘light sensitivity’ with ‘sensitivity to glare’.
· Add ‘visual fatigue’ and ‘visual clutter’ to the list of factors that impact on visual functioning.

**Comment by shawna-slh** [comment]
Point 1. I assume they mean the phrase here:

> This section briefly introduces five categories of visual impairment that impact web use, not including total blindness: Visual acuity (clarity), Light sensitivity, Contrast sensitivity, Field of vision, Color vision

Note that the term "visual functioning" in many contexts is more broad than what we're addressing in this section, e.g., see National Eye Institute Visual Function Questionnaire [(NEI-VFQ) (PDF)](https://nei.nih.gov/sites/default/files/nei-pdfs/vfq_sa.pdf). We have a later section that does address the broader issues, [2.5 Functional Vision](http://w3c.github.io/low-vision-a11y-tf/requirements.html#functional-vision) – that section is where we cover other "factors that impact on visual functioning".

I'm don't see the reasoning behind the suggested change. It seems less descriptive of the content of this section.
However, I agree that it would be good to downplay "categories", so I suggest we change "five categories" to "types":

> This section briefly introduces types of visual impairment that impact web use, not including total blindness: Visual acuity (clarity), Light sensitivity, Contrast sensitivity, Field of vision, Color vision

I would welcome more information from the commenter on the rational for additional changes.

Point 2. 'Light sensitivity' is a less-jargony version of 'Photophobia', which is what we're talking about here. See [References](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/References#Light_Sensitivity). I think 'light sensitivity' is broader than 'sensitivity to glare'. A bright screen in a dark room has no glare, yet can be very problematic. I think light sensitivity includes sensitivity to glare, but sensitivity to glare does not include light sensitivity. (Also, glare is an issue for people w/o low vision.) So I think leave it as is.

Point 3. Fatigue has an entire paragraph – the second one under 2.5 Functional Vision. I don't think "visual clutter" is an "Environmental factor". I think it's an aspect of the design itself - in the same category as text size, font, leading, etc. So I don't think we want to add "visual clutter" to this section. We could bold the word "Fatigue" where it is the first word of the second paragraph.

**Comment by allanj-uaag** [comment]
from Wayne https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Jun/0001.html

> Regarding iterm 68. Sensivity to light and sensivity to glare are different. Light does not need to create glare to cause painful reaction. Glare will usually do it for someone with photosensivity but for people with cloudy corneaa, lense orocular much lower levels of light will cause glare.
> The replacement would leave out an important group of people with photosensitivity for whom avoiding glare is not enough.

**Comment by allanj-uaag** [comment]
Wayne, do you want to have both terms?

**Comment by shawna-slh** [comment]
From 2 June teleconference: There are conditions that cause glare sensitivity and not light sensitivity.
Action: Shawn & Jim work on wording to include glare sensitivity.
Action: Wayne see if issue of visual clutter is covered adequately in user needs.

**Comment by shawna-slh** [comment]
Changed from:
> This section briefly introduces five categories of visual impairment that impact web use...

to:
> This section briefly introduces five types of visual impairment that impact web use...

**Comment by shawna-slh** [comment]
Changed heading from:
>Light Sensitivity

to:
>Light and Glare Sensitivity

Added sentence:
> Glare sensitivity is common with age-related vision changes and cataracts.

Added some [references related to glare sensitivity](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/References#Light_and_Glare_Sensitivity).

OK?

**Comment by shawna-slh** [comment]
I'll close this issue for now (per Jim :-). Anyone can re-open it if needed.
