### ISSUE TITLE
Split from #61 section 2.4.1 lanugage

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#69]
#61

from https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0003.html
Section 2.4.1
· Needs more precise definition of visual acuity. Suggestion: Visual Acuity is a measure of the finest detail a person can perceive.
· 'Therefore, some people will have blurry vision (low visual acuity) no matter what.' This statement is not accurate and therefore not helpful, and should not be included.

**Comment by shawna-slh** [comment]
Point 1: Current wording:

> Visual acuity is the clarity or sharpness of vision. … Measurement of distance visual acuity is based on a standard of 20/20 (6/6 in metric).

We are adding wording that says that this section is not providing formal definitions, etc. We don't necessarily want a good **definition** -- we **do** want a good **explanation** for people who don't know. So maybe we want to add something like - this second sentence:

> Visual acuity is the clarity or sharpness of vision. It relates to the finest detail a person can perceive. … Measurement of distance visual acuity is based on a standard of 20/20 (6/6 in metric).

Point 2: 'Therefore, some people will have blurry vision (low visual acuity) no matter what.' has already been changed to:

>  Therefore, some people will not see small text or fine details at all.

**Comment by shawna-slh** [comment]
Resolved to add sentence 2 June telecon.

**Comment by shawna-slh** [comment]
Done. (will upload new version later today)
