### ISSUE TITLE
Split from #61 2.4.2 language

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#70]
#61 
from https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0003.html

Section 2.4.2
· ‘Light sensitivity’ should be changed to ‘Glare sensitivity’. (Refer to attached article, A review of the impact of glare and fatigue on visual function, p54)

**Comment by shawna-slh** [comment]
This issue is addressed in https://github.com/w3c/low-vision-a11y-tf/issues/68
