### ISSUE TITLE
Split from #61 2.4.3 language

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/low-vision-a11y-tf#71]
#61

from https://lists.w3.org/Archives/Public/public-low-vision-comments/2016AprJun/0003.html

Section 2.4.3
· Contrast sensitivity definition needs to be more succinct. Suggestion –‘Contrast sensitivity determines the retina's ability to detect subtle differences in brightness or shading of grey between targets and their backgrounds’.
(source: Fundamentals for Ophthalmic Technical Personnel by Cassin p167)

**Comment by shawna-slh** [comment]
We are adding wording that says that this section is not providing formal definitions, etc. We don't necessarily want a good **definition** -- we **do want a good explanation** for people who don't know. I agree we could make this clearer - and also maybe more accurate.

How about change the first sentence from:

> Contrast sensitivity is the ability to distinguish bright and dim areas of images, for example, to discern text on a background.

to:

> Contrast sensitivity is the ability to detect differences in brightness between targets and their backgrounds, for example, to discern text from its background.

(We can also add the reference to our resources.)

**Comment by shawna-slh** [comment]
Resolved in 2 June telecon:

> Contrast sensitivity is the ability to detect differences in brightness, for example, to discern text from its background.

**Comment by shawna-slh** [comment]
Done (will upload later today)
