### ISSUE TITLE
Determine if the issues listed on https://github.com/w3c/low-vision-a11y-tf/issues stay open or if we can close these issues.

### ISSUE THREAD

**Issue by ChrisLoiselle** [w3c/low-vision-a11y-tf#96]
Determine if the issues listed on https://github.com/w3c/low-vision-a11y-tf/issues stay open or if we can close these issues.

**Comment by Myndex** [comment]
I've reviewed the issues I opened as far back as 2019, and they are still relevant and need further action.

**Comment by ChrisLoiselle** [comment]
@Myndex we will keep them open. I'll close this particular issue, as you've answered my question.
